language: go

go:
  - "1.10"

sudo: required

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
    - $HOME/.cache/pip
    - $HOME/download

env:
  global:
    - TEST_DIR=/tmp/test_dir/
    - MODULE=xgp
    - TWINE_USERNAME=MaxHalford
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0" CYTHON_VERSION="0.23.4"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
      NUMPY_VERSION="1.14.3" SCIPY_VERSION="1.1.0" CYTHON_VERSION="0.28.2"

stages:
  - test
  - name: pypi
    if: tag IS present

before_script:
  - chmod +x ci_scripts/travis.sh
  - chmod +x ci_scripts/pypi.sh

jobs:
  include:
    - stage: test
      script: ci_scripts/travis.sh
    - stage: pypi
      script: ci_scripts/pypi.sh
